### ISSUE TITLE
Runtime Environment

### ISSUE THREAD

**Issue by lif323** [alexdeng/ghidorah#1] opened 2021-08-09 08:35 UTC
Hello, I'm very interested in your work, but when running this code in r4.1.0 environment, I got the following error reports. Could you tell the cause of the error or the correct version of R language.
```
ERROR: Error in if (x.var <= 0) x.var = sigma^2: missing value where TRUE/FALSE needed
Error in if (x.var <= 0) x.var = sigma^2: missing value where TRUE/FALSE needed
Traceback:

1. evaluateSim(200, 100, 1000, partial(rnorm, mean = 0, sd = 0.1), 
 .     partial(sample, x = c(20, 50, 100, 200), replace = TRUE), 
 .     scale = 1, methods = c(KnownNormalPrior(0.1), methodlist))
2. vapply(methods, purrr::partial(run, traindata = traindata, testdata = testdata), 
 .     FUN.VALUE = rep(0, 9))
3. FUN(X[[i]], ...)
4. eval_tidy(call, mask)
5. (function (cl, traindata, testdata) 
 . {
 .     rmse = rep(NA, 3)
 .     cicov = rep(NA, 3)
 .     vrrate = rep(NA, 3)
 .     mdl = cl$new(traindata)
 .     if (!is.null(mdl$includeVar)) {
 .         mdl$includeVar = TRUE
 .     }
 .     trainedModel = mdl$train()
 .     preds = trainedModel$predict(testdata)
 .     if (!is.atomic(preds)) {
 .         fits = preds$fit
 .         if (!is.null(cl$asymCI) && cl$asymCI) {
.             ciupper = fits$ciupper
 .             cilower = fits$cilower
 .         }
 .         else {
 .             sdfits = sqrt(preds$varfit)
 .             ciupper = fits + 1.96 * sdfits
 .             cilower = fits - 1.96 * sdfits
 .             varfit = preds$varfit
 .         }
 .     }
 .     else {
 .         fits = preds
 .         varfit = testdata$scale^2/testdata$sample_size
 .         ciupper = fits + 1.96 * sqrt(testdata$scale^2/testdata$sample_size)
 .         cilower = fits - 1.96 * sqrt(testdata$scale^2/testdata$sample_size)
 .     }
 .     rmse[1] = caret::RMSE(fits, testdata$mu)
 .     cicov[1] = mean(testdata$mu <= ciupper & testdata$mu >= cilower, 
 .         na.rm = TRUE)
 .     vrrate[1] = mean(varfit/(testdata$scale^2/testdata$sample_size), 
 .         na.rm = TRUE)
 .     selected = testdata$pval < 0.05
 .     rmse[2] = caret::RMSE(fits[selected], testdata$mu[selected])
 .     cicov[2] = mean((testdata$mu <= ciupper & testdata$mu >= 
 .         cilower)[selected], na.rm = TRUE)
 vrrate[2] = mean(varfit[selected]/(testdata$scale^2/testdata$sample_size)[selected], 
 .         na.rm = TRUE)
 .     selected = testdata$pval < 0.01
 .     rmse[3] = caret::RMSE(fits[selected], testdata$mu[selected])
 .     cicov[3] = mean((testdata$mu <= ciupper & testdata$mu >= 
 .         cilower)[selected], na.rm = TRUE)
 .     vrrate[3] = mean(varfit[selected]/(testdata$scale^2/testdata$sample_size)[selected], 
 .         na.rm = TRUE)
 .     c(rev(rmse), rev(cicov), rev(vrrate))
 . })(traindata = traindata, testdata = testdata, ...)
6. trainedModel$predict(testdata)
7. mapply(private$predictfn, x = df$y_scaled, sigma = df$sigma, 
 .     MoreArgs = list(xobs = self$trainingSet$y_scaled, sigmaobs = self$trainingSet$sigma, 
 .         h = c(self$hx, self$hsig)), SIMPLIFY = TRUE)
8. (function (x, sigma, xobs, sigmaobs, h) 
 . {
 .     x.diff = (xobs - x)/(h[1] * sigmaobs)
 .     x.den = exp(-x.diff^2/2)/sigmaobs
 .     sigma.den = exp(-(sigma - sigmaobs)^2/2/h[2]^2)
 .     f.hat = sum(x.den * sigma.den)
 .     f1d.hat = sum(x.den * sigma.den * x.diff/(h[1] * sigmaobs))
 .     f2d.hat = sum(x.den * sigma.den * (x.diff^2 - 1)/(h[1] * 
 .         sigmaobs)^2)
 .     x.mean = x + sigma^2 * f1d.hat/f.hat
.     x.var = sigma^2 * (1 + sigma^2 * (f2d.hat * f.hat - f1d.hat^2)/f.hat^2)
 .     if (x.var <= 0) 
 .         x.var = sigma^2
 .     return(list(mean = x.mean, var = x.var))
```

**Comment by alexdeng** [comment] 2021-08-24 22:22
I tried it on R 4.0.5 and it works. Need to make sure some dependency packages are installed. Will try it on R 4.1

**Comment by alexdeng** [comment] 2021-08-24 22:34
I have no issue running the following code on R4.1.1
You might need to install some extra package if run into any error for missing packages. 

I got warnings about a deprecated function. That's it. Will find source of this warning in xgboost. But other than that I cannot reproduce your error.  
[15:35:09] WARNING: amalgamation/../src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
Called from: chr_unserialise_unicode(names2(data))

```
install.packages(c("xgboost",'nnls','truncnorm','caret'))

library(tidyverse)
options(digits=3)
# load all implemented methods
source("methods/BaselineUnAdjusted/baselineUnajusted.R")
source("methods/knownprior/knownprior.R")
source("methods/split/simple_Splitting.R")
source("methods/postselect/postselect.R")
source("methods/split/boost_Splitting.R")
source("methods/EBmle/ebmle.R")
source("methods/BFBound/bfbound.R")
source("methods/MixturePrior/mixture.R")
source("methods/split/TARwES.R")
source("methods/EBHuberSURE/EBHuberSURE.R")

source("simulation/simulation.R")

# Define list of method to test
# baselineAnadjust: unadjusted naive MLE
# simpleSplitting: RwES with linear regression
# TARwESSplitting: TARwES
# NormalPriorEB: EB using normal prior (James-Stein)
# LaplacePriorEB: EB using Laplace prior
# ZeroNormalLaplaceMixEB: Ghidorah with three heads
# HuberPriorEB: EB using Huber prior
# GhidorahSplitting: TARwES+ where Ghidorah is used as one of the feature
# postSelectZCut(1.96): CMLE using z-score 1.96 as cutoff

# With CMLE the simulation study could run quite slow. I recommend to run without CMLE at first if you are impatient :)
methodlist = c(baselineUnadjust, simpleSplitting, bstSplitting, TARwESSplitting, NormalPriorEB, LaplacePriorEB, ZeroNormalLaplaceMixEB, HuberPriorEB, GhidorahSplitting, postSelectZCut(1.96))
#methodlist = c(baselineUnadjust, simpleSplitting,bstSplitting, TARwESSplitting, NormalPriorEB, LaplacePriorEB, ZeroNormalLaplaceMixEB, HuberPriorEB, GhidorahSplitting)


# Simulation Study 1
# note the set.seed for replication
set.seed(1)
res = evaluateSim(200, 100, 1000, partial(rnorm,mean=0, sd=0.1), partial(sample,x=c(20,50,100,200),replace=TRUE), scale = 1, methods = c(KnownNormalPrior(0.1),methodlist))
res
```

**Comment by alexdeng** [comment] 2021-09-07 19:51
@lif323  can you confirm it works for you? Or let me know how to reproduce your error?

**Comment by lif323** [comment] 2021-09-08 10:57
@alexdeng Thank you very much. I found that it was the fork version of current repository that reported the error, that is, the version given in the paper. The above error occurred in this version.
https://github.com/lycbest1-yicheng/ghidorah

**Comment by lif323** [comment] 2021-09-08 10:58
@alexdeng Thank you very much. I found that it was the fork version of the current repository that reported the error, that is, the version given in the paper. The above error occurred in this version.
https://github.com/lycbest1-yicheng/ghidorah

**Comment by alexdeng** [comment] 2021-09-10 04:33
Yicheng is my coauthor and his main change in his fork is to add NEST method. If you are mainly interested in the method for this paper, you can use this repo. Please reach out to Yicheng for your error experienced in his fork.

**Comment by alexdeng** [comment] 2021-09-10 04:33
I will close this issue here.

**Closed as completed by alexdeng** 2021-09-10 04:33 UTC
